version: '3.4'

services:
  db:
    container_name: graphql_rpi_db_v2
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
      - PGDATA
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  graphql:
    container_name: graphql_rpi_v2
    image: node-graphql-results
    build: .
    env_file:
      - .env
    restart: always
    environment:
      - WAIT_HOSTS=db:5432
      - NODE_ENV
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
      - PGDATA
      - PORT
    ports:
      - ${PORT}:4000
    depends_on:
      - db
  pgadmin4:
    container_name: graphql_rpi_pgadmin_v2
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'dbuser@localhost.com'
      PGADMIN_DEFAULT_PASSWORD: '1q2w34r5t'
      PGADMIN_LISTEN_PORT: '5050'
    ports:
      - 5050:5050
    depends_on:
      - db
volumes:
  pgdata:
