version: '3.4'

services:
  graphql:
    container_name: graphql_rpi_v2
    image: node-graphql-results
    build: .
    env_file:
      - .env
    restart: always
    environment:
      - WAIT_HOSTS=db:5432
      - NODE_ENV
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
      - PGDATA
      - PORT
    ports:
      - ${PORT}:4000
