version: '3.4'

services:
  pgadmin4:
    container_name: graphql_rpi_pgadmin_v2
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'dbuser@localhost.com'
      PGADMIN_DEFAULT_PASSWORD: '1q2w34r5t'
      PGADMIN_LISTEN_PORT: '5050'
    ports:
      - 5050:5050
